### ISSUE TITLE
How to debug the code?

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode-mock-debug#10]
How do i debug the code in mockDebug.ts?

I have launched VS Code using the ```Extension + Server``` debug configuration and added the necessary breakpoints. In the new VS Code window debugging a ```readme.md``` works as expected, however no breakpoints in the extension code are hit?

***Note: The following is displayed in the VS Code debug console***
```
Error: certificate has expired
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
Error: certificate has expired
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
```

**Comment by weinand** [comment]
@DonJayamanne this works fine for me.
But you have to make sure that the launch config for your "readme.md" contains a `"debugServer": 4711"`.

**Comment by DonJayamanne** [comment]
Thanks
