### ISSUE TITLE
Cannot find module 'supports-color'

### ISSUE THREAD

**Issue by darksectordds** [microsoft/vscode-mock-debug#31]
Hello here. There is a need for a debugger for a specific device. I started by learning from here https://code.visualstudio.com/api/extension-guides/debugger-extension , but almost a day can not solve this problem.

`Exception has occurred: Error
Error: Cannot find module 'supports-color'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Function.define._installInterceptor.i._load (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:491:111)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at n (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:488)
    at Object.<anonymous> (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\http-proxy-agent\node_modules\debug\src\node.js:29:23)
    at Object.<anonymous> (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\http-proxy-agent\node_modules\debug\src\node.js:188:3)
    at Module.t._initNodeRequire.o._compile (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:713)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Function.define._installInterceptor.i._load (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:491:111)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at n (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:488)
    at Object.<anonymous> (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\http-proxy-agent\node_modules\debug\src\index.js:9:20)
    at Object.<anonymous> (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\http-proxy-agent\node_modules\debug\src\index.js:12:3)
    at Module.t._initNodeRequire.o._compile (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:713)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Function.define._installInterceptor.i._load (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:491:111)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at n (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:488)
    at Object.<anonymous> (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\http-proxy-agent\index.js:11:13)
    at Object.<anonymous> (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\http-proxy-agent\index.js:113:3)
    at Module.t._initNodeRequire.o._compile (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:713)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Function.define._installInterceptor.i._load (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:491:111)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at n (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:488)
    at Object.<anonymous> (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\index.js:15:22)
    at Object.<anonymous> (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\index.js:115:3)
    at Module.t._initNodeRequire.o._compile (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:713)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Function.define._installInterceptor.i._load (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:491:111)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at t.load (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:247)
    at e.load (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:13:587)
    at i (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:28:371)
    at Object.errorback (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:28:492)
    at e.triggerErrorback (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:13:952)
    at c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:13:657
    at c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:617
    at a (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:18:530)
    at ReadFileContext.callback (c:\Users\DDS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:18:614)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:235:13)`

Version: 1.36.1 (user setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

> node --version
v11.8.0

**Comment by darksectordds** [comment]
if diable breakpoints type "All Exceptions" then work fine.

**Comment by kjeremy** [comment]
Seeing the same thing on vscode 1.39 but disabling break points does not let me work around it.

**Comment by estarkey7** [comment]
I'm stuck with this error also. I just can't work around this as I try to write an in circuit emulator debugger.

**Comment by weinand** [comment]
Please provide steps so that I can reproduce what you are trying to do.

**Comment by nimpossible** [comment]
Try unchecking the **All Exceptions** checkbox under Breakpoints palette. It will work.

**Comment by as1ndu** [comment]
I have been stuck withthis for months. Any solutions?

**Comment by kramsram** [comment]
Just continuing the session by choosing to run on the break seems to work for me. The breakpoints seem to work as well after this. It is still annoying to have to keep pushing the button every I time start a session.

**Comment by weinand** [comment]
Recently we have switched to a new JS debugger. So this problem should no longer occur.

**Comment by Rainnut** [comment]
how to resolve problem? me too

**Comment by zokizuan** [comment]
how to resolve problem? me too


![image](https://user-images.githubusercontent.com/7491735/120662898-24bed200-c4a7-11eb-8656-106a4fdf7d26.png)

**Comment by as1ndu** [comment]
> 
> 
> Try unchecking the **All Exceptions** checkbox under Breakpoints palette inside VS Code. It will work.

This seemed to solve it for me

**Comment by calidion** [comment]
encountered the same problem.

```
Exception has occurred: Error: Cannot find module 'supports-color'
Require stack:
- /usr/share/code/resources/app/node_modules.asar/http-proxy-agent/node_modules/debug/src/node.js
- /usr/share/code/resources/app/node_modules.asar/http-proxy-agent/node_modules/debug/src/index.js
- /usr/share/code/resources/app/node_modules.asar/http-proxy-agent/index.js
- /usr/share/code/resources/app/node_modules.asar/vscode-proxy-agent/index.js
- /usr/share/code/resources/app/out/bootstrap-amd.js
- /usr/share/code/resources/app/out/bootstrap-fork.js
  at Function._resolveFilename (internal/modules/cjs/loader.js:844:17)
    at internal/modules/cjs/loader.js:737:27
    at Function._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:899:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/share/code/resources/app/node_modules.asar/http-proxy-agent/node_modules/debug/src/node.js:29:23)
    at Module._compile (internal/modules/cjs/loader.js:1014:30)
    at Object..js (internal/modules/cjs/loader.js:1051:10)
    at Module.load (internal/modules/cjs/loader.js:862:32)
    at internal/modules/cjs/loader.js:774:14
    at Function._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:899:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/share/code/resources/app/node_modules.asar/http-proxy-agent/node_modules/debug/src/index.js:9:20)
    at Module._compile (internal/modules/cjs/loader.js:1014:30)
    at Object..js (internal/modules/cjs/loader.js:1051:10)
    at Module.load (internal/modules/cjs/loader.js:862:32)
    at internal/modules/cjs/loader.js:774:14
    at Function._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:899:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/share/code/resources/app/node_modules.asar/http-proxy-agent/index.js:11:13)
    at Module._compile (internal/modules/cjs/loader.js:1014:30)
    at Object..js (internal/modules/cjs/loader.js:1051:10)
    at Module.load (internal/modules/cjs/loader.js:862:32)
    at internal/modules/cjs/loader.js:774:14
    at Function._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:899:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/share/code/resources/app/node_modules.asar/vscode-proxy-agent/index.js:15:22)
    at Module._compile (internal/modules/cjs/loader.js:1014:30)
    at Object..js (internal/modules/cjs/loader.js:1051:10)
    at Module.load (internal/modules/cjs/loader.js:862:32)
    at internal/modules/cjs/loader.js:774:14
    at Function._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:899:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at r (/usr/share/code/resources/app/out/vs/loader.js:20:263)
    at t.load (/usr/share/code/resources/app/out/vs/loader.js:16:979)
    at e.load (/usr/share/code/resources/app/out/vs/loader.js:13:998)
    at i (/usr/share/code/resources/app/out/vs/loader.js:30:259)
    at s._loadModule (/usr/share/code/resources/app/out/vs/loader.js:30:393)
    at s._resolve (/usr/share/code/resources/app/out/vs/loader.js:31:914)
    at s.defineModule (/usr/share/code/resources/app/out/vs/loader.js:26:184)
    at n (/usr/share/code/resources/app/out/vs/loader.js:33:308)
    at c (/usr/share/code/resources/app/out/vs/loader.js:17:806)
    at Object.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1053:207)
    at Object.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1096:61)
    at t._createAndEvalScript (/usr/share/code/resources/app/out/vs/loader.js:17:850)
    at /usr/share/code/resources/app/out/vs/loader.js:17:487
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
```

**Comment by calidion** [comment]
encountered the same problem.

```
Exception has occurred: Error: Cannot find module 'supports-color'
Require stack:
- /usr/share/code/resources/app/node_modules.asar/http-proxy-agent/node_modules/debug/src/node.js
- /usr/share/code/resources/app/node_modules.asar/http-proxy-agent/node_modules/debug/src/index.js
- /usr/share/code/resources/app/node_modules.asar/http-proxy-agent/index.js
- /usr/share/code/resources/app/node_modules.asar/vscode-proxy-agent/index.js
- /usr/share/code/resources/app/out/bootstrap-amd.js
- /usr/share/code/resources/app/out/bootstrap-fork.js
  at Function._resolveFilename (internal/modules/cjs/loader.js:844:17)
    at internal/modules/cjs/loader.js:737:27
    at Function._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:899:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/share/code/resources/app/node_modules.asar/http-proxy-agent/node_modules/debug/src/node.js:29:23)
    at Module._compile (internal/modules/cjs/loader.js:1014:30)
    at Object..js (internal/modules/cjs/loader.js:1051:10)
    at Module.load (internal/modules/cjs/loader.js:862:32)
    at internal/modules/cjs/loader.js:774:14
    at Function._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:899:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/share/code/resources/app/node_modules.asar/http-proxy-agent/node_modules/debug/src/index.js:9:20)
    at Module._compile (internal/modules/cjs/loader.js:1014:30)
    at Object..js (internal/modules/cjs/loader.js:1051:10)
    at Module.load (internal/modules/cjs/loader.js:862:32)
    at internal/modules/cjs/loader.js:774:14
    at Function._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:899:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/share/code/resources/app/node_modules.asar/http-proxy-agent/index.js:11:13)
    at Module._compile (internal/modules/cjs/loader.js:1014:30)
    at Object..js (internal/modules/cjs/loader.js:1051:10)
    at Module.load (internal/modules/cjs/loader.js:862:32)
    at internal/modules/cjs/loader.js:774:14
    at Function._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:899:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/share/code/resources/app/node_modules.asar/vscode-proxy-agent/index.js:15:22)
    at Module._compile (internal/modules/cjs/loader.js:1014:30)
    at Object..js (internal/modules/cjs/loader.js:1051:10)
    at Module.load (internal/modules/cjs/loader.js:862:32)
    at internal/modules/cjs/loader.js:774:14
    at Function._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:899:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at r (/usr/share/code/resources/app/out/vs/loader.js:20:263)
    at t.load (/usr/share/code/resources/app/out/vs/loader.js:16:979)
    at e.load (/usr/share/code/resources/app/out/vs/loader.js:13:998)
    at i (/usr/share/code/resources/app/out/vs/loader.js:30:259)
    at s._loadModule (/usr/share/code/resources/app/out/vs/loader.js:30:393)
    at s._resolve (/usr/share/code/resources/app/out/vs/loader.js:31:914)
    at s.defineModule (/usr/share/code/resources/app/out/vs/loader.js:26:184)
    at n (/usr/share/code/resources/app/out/vs/loader.js:33:308)
    at c (/usr/share/code/resources/app/out/vs/loader.js:17:806)
    at Object.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1053:207)
    at Object.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1096:61)
    at t._createAndEvalScript (/usr/share/code/resources/app/out/vs/loader.js:17:850)
    at /usr/share/code/resources/app/out/vs/loader.js:17:487
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
```

**Comment by weinand** [comment]
What exactly are you trying to do when this happens?
Are you debugging your own code or extension?

**Comment by Muneeza93** [comment]
Hi guys when i try to install packages with npm it returns for me this error "UnhandledPromiseRejectionWarning: Error: Cannot find module 'color-support'
Require stack:C:\Program Files\nodejs\node_modules\npm\node_modules\gauge\has-color.js"
i tried to install the 'color-support package i still run into the same error.
Any assistance is highly appreciated
