### ISSUE TITLE
The build/run instructions are incomplete and flawed.

### ISSUE THREAD

**Issue by billw2012** [microsoft/vscode-mock-debug#38]
I had to run yarn manually (after installing it), and the default runMode is set to external which doesn't allow you to debug the adapter when you press F5. 
It should be setup for debugging not testing by default, but even if not, it should at least explicitly say the runMode needs to be changed so that debugging will work.
People writing debug adapters for VSCode aren't going to be javascript or node.js experts (or even novices) on a lot of cases, they are just trying to get *their* language/whatever to work. 
The examples and instructions should reflect that.

**Comment by ddotlic** [comment]
@billw2012 I _just_ tried debugging the extension per the readme in the project itself and have not had luck. Looking at `package.json` I cannot figure out which of the scripts I should run.

Care to share what you did to get this working? By this I mean achieving what the second part of the readme claims, which is debugging the debug adapter itself in another instance of VS Code?

Thanks in advance!

**Comment by ddotlic** [comment]
To anyone reading this:

1. Have yarn installed on your system
2. Run yarn install
3. Choose "Extension" debug config in the "normal" VS Code instance and run/debug that
4. The rest of the instructions are correct, just add `readme.md` and run `F5` to debug it

**Comment by ddotlic** [comment]
Finally figured it out...

So, the key is the hint from @billw2012 (thanks!) about `runMode` - this is in the _source_ of the debug adapter, in the `mockRuntime.ts`. Setting the default value to `inline` works for me, `external` did not work.

**Comment by billw2012** [comment]
Huh, okay I didn't try `inline`, I assumed that this would not work as I assumed it instantiates the adapter in the debug target.

**Comment by ddotlic** [comment]
>  it instantiates the adapter in the debug target.

@billw2012 What did you try? What worked for you?

**Comment by billw2012** [comment]
Using runMode `server` and `Extension` debug config seemed to work,

**Comment by billw2012** [comment]
I think current steps to run from scratch would be then:
1. Clone the repo
2. Install `yarn`
3. Run `yarn` in root
4. Change `runMode` in `mockRuntime.ts` to `"inline"` (or possibly `"server"`)
5. Make sure `Extension` debug config is selected and press F5

**Comment by weinand** [comment]
Please see https://code.visualstudio.com/api/extension-guides/debugger-extension#the-mock-debug-extension

**Comment by jdeantoni** [comment]
Hi,

I tried to follow @billw2012  instructions and I still end up with:
![image](https://user-images.githubusercontent.com/6162718/141134222-4cbe8f35-8689-4b0e-8730-1dd3f0c8d2f7.png)

any idea ?

**Comment by weinand** [comment]
@jdeantoni are you on Windows?

**Comment by jdeantoni** [comment]
No, i’m on open suse. An error message also tell me cannot connect to localhost:aNumber… I can give you the exact message if needed

**Comment by weinand** [comment]
But you are using the standard VS Code?

**Comment by jdeantoni** [comment]
Yes, I do. I'm using this version of vscode: 
![image](https://user-images.githubusercontent.com/6162718/141173094-c45d5eeb-ec56-4331-b00f-703ea47f9f68.png)

also here is the exact stack frame I have:

`
[2021-11-10 19:37:38.935] [renderer1] [error] [Extension Host] Error: Could not connect to debug target at http://localhost:53556: Could not find any debuggable target
	at Object.retryGetNodeEndpoint (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1396584)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async f.launchProgram (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1412163)
	at async f.launch (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1436173)
	at async t.Binder.captureLaunch (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1227825)
	at async t.Binder._launch (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1227370)
	at async Promise.all (index 1)
	at async t.Binder._boot (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1226422)
	at async t.default._onMessage (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1319096)
[2021-11-10 19:37:38.962] [renderer1] [error] Error processing attach: Error: Could not connect to debug target at http://localhost:53556: Could not find any debuggable target
	at Object.retryGetNodeEndpoint (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1396584)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async f.launchProgram (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1412163)
	at async f.launch (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1436173)
	at async t.Binder.captureLaunch (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1227825)
	at async t.Binder._launch (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1227370)
	at async Promise.all (index 1)
	at async t.Binder._boot (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1226422)
	at async t.default._onMessage (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1319096): Error: Error processing attach: Error: Could not connect to debug target at http://localhost:53556: Could not find any debuggable target
	at Object.retryGetNodeEndpoint (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1396584)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async f.launchProgram (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1412163)
	at async f.launch (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1436173)
	at async t.Binder.captureLaunch (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1227825)
	at async t.Binder._launch (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1227370)
	at async Promise.all (index 1)
	at async t.Binder._boot (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1226422)
	at async t.default._onMessage (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1319096)
    at o.handleErrorResponse (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1024:33974)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1024:33280
    at async o.launchOrAttach (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1024:26037)
    at async N.launchOrAttach (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1906:12304)
    at async J.launchOrAttachToSession (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1906:43188)
`

**Comment by jdeantoni** [comment]
Nope , on open suse…

Short message from a mobile device

**Comment by weinand** [comment]
I cannot reproduce the problem.
Here is what I did on Ubuntu 21.10 LTE:
- in a new directory `git clone https://github.com/microsoft/vscode-mock-debug.git`
- opened new folder `vscode-mock-debug` in VS Code 1.61.2
- VS Code asked whether to install the recommended extensions: I answered "yes"
- I opened new Terminal in VS Code and ran `yarn`
- switched to VS Code's "Run and Debug" viewlet
- selected launch configuration "Extension" in the debug drop down menu and then pressed the "play" button

A new window appeared where I selected the "readme.md" file and then selected "Debug" from the editor's "Run and Debug" menu. 
-> Mock debug stopped on the first line

**Comment by jdeantoni** [comment]
@weinand , thanks for the help. I have the problem only one of my machines :-/ On the others it works like for you.
I'll check if the problem comes from another extension or perhaps the firewall or so and I'll get back to you.
If you have any idea on what to check first, do not hesitate to tell me.

**Comment by weinand** [comment]
The firewall might be the culprit because in your stack trace I see a
> Error: Could not connect to debug target at http://localhost:53556: Could not find any debuggable target at Object.retryGetNodeEndpoint
